### ISSUE TITLE
Problema ao tentar usar o authenticate do exemplo

### ISSUE THREAD

**Issue by Katekko** [acesso-io/unico_check_flutter#7]
Parece que o auth está tentando utilizar o liveness, não sei se é normal mas toda vez que vai pra completar o auth ele da null exception e fecha o app

Está dando erro dentro do method channel ( ai como eu não tenho expertise não consigo ajudar )

![image](https://user-images.githubusercontent.com/13632735/117538160-48434980-afdb-11eb-83bb-94e18f26a12d.png)

**Comment by Diniz-Lucas** [comment]
Identificamos o problema, o mesmo estava vindo da SDK...  vamos subir na próxima Release assim que for publicada a release no Android

**Comment by Diniz-Lucas** [comment]
Esta versão resolve estes problemas entre outros como a fricção na implementação com iOS 
https://pub.dev/packages/unico_check

abç
